"use client"

import { useEffect, useState } from "react"
import { TopBar } from "@/components/TopBar"

const REVELATION_API_URL = process.env.NEXT_PUBLIC_REVELATION_API_URL ?? "http://localhost:8000"

interface AssetRef {
  asset_id: string
  role: string
  importance: string
}

interface SectionDesign {
  id: string
  section_id: string
  visual_role: string[]
  visual_priority: string
  composition_mode: string
  asset_refs: AssetRef[]
  text_density: string
  image_density: string
  diagram_strategy: string | null
  whitespace: string
  contrast: string
  repetition: string[]
  heading_role: string | null
  body_role: string | null
  caption_role: string | null
  typography_hierarchy: string
  color_strategy: string | null
  change_type: string
  rationale: string | null
}

interface DesignExclusion {
  section_id: string
  reason: string
  description: string
}

interface DesignConstraint {
  description: string
  strength: string
  source: string
}

interface DesignIssue {
  type: string
  description: string
  section_id: string | null
}

interface DesignIntent {
  id: string
  brand_id: string | null
  brand_version: string | null
  design_state_version: number | null
  visual_language: string[]
  composition_strategy: string
  rhythm: string
  density: string
  typography_hierarchy: string
  color_strategy: string
  grid_strategy: string
  whitespace_strategy: string
  section_designs: SectionDesign[]
  excluded_sections: DesignExclusion[]
  constraints: DesignConstraint[]
  design_issues: DesignIssue[]
}

interface NarrativeSection {
  id: string
  role: string
  purpose: string
  priority: string
}

interface NarrativePlan {
  objective: string
  audience: string
  sections: NarrativeSection[]
}

interface PlanResult {
  design_intent: DesignIntent
  narrative_plan: NarrativePlan
  validation: {
    ok: boolean
    findings: { code: string; severity: string; field: string; message: string }[]
  }
  request_id: string
}

interface Trace {
  request_id: string
  project_id: string
  model: string
  validation_ok: boolean
  latency_ms: number
}

// ADOS-M3.4 — the developer-facing way to inspect
//   SemanticIntent -> ContentIntelligenceModel -> NarrativePlan
//   -> Brand DNA -> Creative Direction -> Design State
//   -> DesignIntent -> Validation -> Trace
// No geometry, no PagePlan, no CommandIntent is generated by this page's endpoint.
export default function DevDesignIntentPage() {
  const [projectId, setProjectId] = useState("")
  const [documentId, setDocumentId] = useState("")
  const [documentTypeId, setDocumentTypeId] = useState("portfolio")
  const [audience, setAudience] = useState("prospective_client")
  const [purpose, setPurpose] = useState("introduce_project")
  const [rawText, setRawText] = useState(
    "Residential development in Budapest. 84 apartments. GFA of 13,100 m². The project creates a strong connection to the landscape."
  )
  const [result, setResult] = useState<PlanResult | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [traces, setTraces] = useState<Trace[]>([])

  async function loadTraces() {
    try {
      const res = await fetch(`${REVELATION_API_URL}/api/v2/ados-projects/design/traces?limit=20`)
      if (res.ok) setTraces((await res.json()).traces)
    } catch {
      // dev-only convenience
    }
  }

  useEffect(() => {
    loadTraces()
  }, [])

  async function submit() {
    if (!projectId.trim()) {
      setError("A project id is required — create one in /projects first.")
      return
    }
    setBusy(true)
    setError(null)
    setResult(null)
    try {
      const res = await fetch(
        `${REVELATION_API_URL}/api/v2/ados-projects/${encodeURIComponent(projectId)}/design/intent`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            semantic_intent: { explicit: { audience: audience || undefined, purpose: purpose || undefined } },
            document_id: documentId || undefined,
            document_type_id: documentTypeId || undefined,
            raw_documents: rawText.trim() ? [{ source_id: "dev-source", text: rawText }] : [],
          }),
        }
      )
      const data = await res.json()
      if (!res.ok) {
        setError(`${res.status} ${JSON.stringify(data.detail)}`)
        return
      }
      setResult(data)
      await loadTraces()
    } catch (e) {
      setError(String(e))
    } finally {
      setBusy(false)
    }
  }

  function narrativeSection(sectionId: string): NarrativeSection | undefined {
    return result?.narrative_plan.sections.find((s) => s.id === sectionId)
  }

  return (
    <div className="flex h-screen flex-col">
      <TopBar />

      <div className="border-b border-line bg-warn-bg px-4 py-2 text-[12px] font-medium text-warn">
        DEV — ADOS-M3.4 Design Intent inspection. Semantic visual strategy only —
        no coordinates, no PagePlan, no CommandIntent has been generated here.
      </div>

      <main className="flex-1 overflow-auto p-4">
        <div className="mb-4 flex flex-col gap-3 text-[12.5px]">
          <div className="flex flex-wrap items-end gap-3">
            <label className="flex flex-col gap-1">
              <span className="text-[10.5px] uppercase tracking-[.05em] text-mute">Project id</span>
              <input
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
                placeholder="required"
                className="w-64 rounded-[7px] border border-line-strong bg-paper-raised px-2 py-[5px] font-mono text-[11.5px]"
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-[10.5px] uppercase tracking-[.05em] text-mute">Document id (optional — for Brand/Direction/DesignState)</span>
              <input
                value={documentId}
                onChange={(e) => setDocumentId(e.target.value)}
                className="w-56 rounded-[7px] border border-line-strong bg-paper-raised px-2 py-[5px] font-mono text-[11.5px]"
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-[10.5px] uppercase tracking-[.05em] text-mute">Document type</span>
              <input
                value={documentTypeId}
                onChange={(e) => setDocumentTypeId(e.target.value)}
                className="w-40 rounded-[7px] border border-line-strong bg-paper-raised px-2 py-[5px] font-mono text-[11.5px]"
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-[10.5px] uppercase tracking-[.05em] text-mute">Audience</span>
              <input
                value={audience}
                onChange={(e) => setAudience(e.target.value)}
                className="w-44 rounded-[7px] border border-line-strong bg-paper-raised px-2 py-[5px] font-mono text-[11.5px]"
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-[10.5px] uppercase tracking-[.05em] text-mute">Purpose</span>
              <input
                value={purpose}
                onChange={(e) => setPurpose(e.target.value)}
                className="w-44 rounded-[7px] border border-line-strong bg-paper-raised px-2 py-[5px] font-mono text-[11.5px]"
              />
            </label>
          </div>

          <label className="flex flex-col gap-1">
            <span className="text-[10.5px] uppercase tracking-[.05em] text-mute">
              Simulated source text (feeds M3.2 content resolution)
            </span>
            <textarea
              value={rawText}
              onChange={(e) => setRawText(e.target.value)}
              rows={3}
              className="rounded-[7px] border border-line-strong bg-paper-raised px-2.5 py-[6px] font-mono text-[12px]"
            />
          </label>

          <button
            onClick={submit}
            disabled={busy}
            className="w-fit rounded-[7px] bg-accent px-3 py-[6px] font-medium text-white disabled:opacity-40"
          >
            {busy ? "Designing…" : "POST /design/intent"}
          </button>
        </div>

        {error ? <p className="mb-3 text-[12.5px] text-crit">{error}</p> : null}

        {result ? (
          <>
            <div className="mb-4 rounded-[10px] border border-line-strong bg-paper-raised p-3">
              <p className="mb-1 text-[10.5px] font-semibold uppercase tracking-[.05em] text-mute">
                Document-level strategy
              </p>
              <p className="text-[12px] text-ink-soft">
                composition = <span className="font-mono">{result.design_intent.composition_strategy}</span> ·
                rhythm = <span className="font-mono">{result.design_intent.rhythm}</span> · density ={" "}
                <span className="font-mono">{result.design_intent.density}</span> · typography ={" "}
                <span className="font-mono">{result.design_intent.typography_hierarchy}</span>
              </p>
              <p className="mt-1 text-[12px] text-ink-soft">
                colour = <span className="font-mono">{result.design_intent.color_strategy}</span> · grid ={" "}
                <span className="font-mono">{result.design_intent.grid_strategy}</span> · whitespace ={" "}
                <span className="font-mono">{result.design_intent.whitespace_strategy}</span>
              </p>
              <p className="mt-1 text-[12px] text-ink-soft">
                visual_language: {result.design_intent.visual_language.join(", ") || "(none — no brand attached)"}
              </p>
              <p className="mt-1 text-[11px] text-mute">
                brand: {result.design_intent.brand_id ?? "(none)"} · design_state_version:{" "}
                {result.design_intent.design_state_version ?? "(none — fresh design)"}
              </p>
            </div>

            <div className="mb-4 rounded-[10px] border border-line-strong bg-paper-raised p-3">
              <p className="mb-1 text-[10.5px] font-semibold uppercase tracking-[.05em] text-mute">
                Narrative → Visual mapping
              </p>
              {result.design_intent.section_designs.map((sd) => {
                const ns = narrativeSection(sd.section_id)
                return (
                  <div key={sd.id} className="mb-2 border-b border-line pb-2 last:border-0">
                    <p className="text-[12px] text-ink-soft">
                      <span className="font-medium">{ns?.role ?? "?"}</span>
                      {" → "}
                      <span className="font-mono">{sd.visual_role.join(" + ")}</span>
                      {" · priority "}
                      <span className="font-mono">{sd.visual_priority}</span>
                      {" · "}
                      <span className="font-mono">{sd.composition_mode}</span>
                    </p>
                    <p className="text-[11.5px] text-mute">
                      text={sd.text_density}, image={sd.image_density}, whitespace={sd.whitespace}, contrast=
                      {sd.contrast}, typography={sd.typography_hierarchy}
                      {sd.heading_role ? `, heading_role=${sd.heading_role}` : ""}
                      {sd.body_role ? `, body_role=${sd.body_role}` : ""}
                    </p>
                    {sd.asset_refs.length > 0 ? (
                      <p className="text-[11.5px] text-ink-soft">
                        assets: {sd.asset_refs.map((a) => `${a.asset_id} (${a.role}, ${a.importance})`).join("; ")}
                      </p>
                    ) : (
                      <p className="text-[11px] text-mute">no assets assigned</p>
                    )}
                    {sd.rationale ? <p className="text-[11.5px] italic text-ink-soft">rationale: {sd.rationale}</p> : null}
                  </div>
                )
              })}
              {result.design_intent.excluded_sections.map((ex) => {
                const ns = narrativeSection(ex.section_id)
                return (
                  <p key={ex.section_id} className="text-[12px] text-mute">
                    <span className="font-medium">{ns?.role ?? ex.section_id}</span> — excluded ({ex.reason}
                    {ex.description ? `: ${ex.description}` : ""})
                  </p>
                )
              })}
            </div>

            <div className="mb-4 grid grid-cols-1 gap-3 lg:grid-cols-2">
              <div className="rounded-[10px] border border-line-strong bg-paper-raised p-3">
                <p className="mb-1 text-[10.5px] font-semibold uppercase tracking-[.05em] text-mute">Constraints</p>
                {result.design_intent.constraints.map((c, i) => (
                  <p key={i} className="text-[12px] text-ink-soft">
                    <span className={c.strength === "hard" ? "font-medium text-crit" : "text-mute"}>{c.strength}</span>{" "}
                    {c.description} {c.source ? `(${c.source})` : ""}
                  </p>
                ))}
                {result.design_intent.constraints.length === 0 && <p className="text-[12px] text-mute">None.</p>}
              </div>

              <div className="rounded-[10px] border border-line-strong bg-paper-raised p-3">
                <p className="mb-1 text-[10.5px] font-semibold uppercase tracking-[.05em] text-mute">Design issues</p>
                {result.design_intent.design_issues.map((issue, i) => (
                  <p key={i} className="text-[12px] text-crit">
                    {issue.type}: <span className="text-ink-soft">{issue.description}</span>
                  </p>
                ))}
                {result.design_intent.design_issues.length === 0 && <p className="text-[12px] text-mute">None.</p>}
              </div>
            </div>

            <div className="mb-4 rounded-[10px] border border-line-strong bg-paper-raised p-3">
              <p className="mb-1 text-[10.5px] font-semibold uppercase tracking-[.05em] text-mute">
                Validation — {result.validation.ok ? "ok" : "has findings"}
              </p>
              {result.validation.findings.length === 0 ? (
                <p className="text-[12px] text-mute">No findings.</p>
              ) : (
                result.validation.findings.map((f, i) => (
                  <p key={i} className="text-[12px] text-ink-soft">
                    <span className="font-mono text-[10.5px] text-mute">{f.code}</span>{" "}
                    <span className="font-medium">{f.severity}</span> {f.field}: {f.message}
                  </p>
                ))
              )}
            </div>

            <pre className="mb-4 overflow-auto rounded-[10px] border border-line-strong bg-paper-raised p-3 text-[11px] leading-relaxed text-ink-soft">
              {JSON.stringify(result, null, 2)}
            </pre>
          </>
        ) : (
          <p className="mb-4 text-[12.5px] text-mute">
            Enter a project id and POST /design/intent. Content resolves through the M3.2 pipeline and
            narrative through M3.3, exactly as /dev/narrative does; this page adds Brand DNA + Creative
            Direction + Design State and produces the resulting visual strategy.
          </p>
        )}

        <div>
          <p className="mb-1 text-[10.5px] font-semibold uppercase tracking-[.05em] text-mute">
            Recent designs (this process, in memory)
          </p>
          {traces.length === 0 ? (
            <p className="text-[12px] text-mute">None yet.</p>
          ) : (
            <div className="space-y-0.5">
              {traces.map((t) => (
                <div key={t.request_id} className="flex items-center gap-2 text-[11.5px]">
                  <span className={t.validation_ok ? "text-mute" : "text-crit"}>
                    {t.validation_ok ? "ok" : "findings"}
                  </span>
                  <span className="truncate text-ink-soft">{t.project_id}</span>
                  <span className="text-mute">{t.model}</span>
                  <span className="ml-auto flex-shrink-0 text-mute">{t.latency_ms.toFixed(0)}ms</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  )
}
