"""
brand/export/exporters.py

Getting the brand out of ADOS and into the tools that consume it.

Every exporter takes a :class:`TokenSet` (or a :class:`Brand` where the export
is of the definition itself) and writes a file. None of them re-derives a
value: an exporter that computed anything would be a second implementation of
the resolver, and the two would diverge on the first change.

Two of the exporters need a browser. Rasterising an SVG and printing HTML to
PDF are both jobs a browser already does correctly, and reimplementing either
would mean shipping a second, worse renderer. Chromium is optional: where it
is absent the exporter says so and the rest of the package still builds, in
the same way ``pyshacl`` is optional to the rule engine.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from brand.models.brand import Brand
from brand.models.tokens import TokenSet

#: Where the bundled Chromium lives in this environment. Checked, never assumed.
_CHROMIUM_CANDIDATES = (
    "/opt/pw-browsers/chromium",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    "/usr/bin/google-chrome",
)


class ExportUnavailable(RuntimeError):
    """An export needs a tool that is not installed."""


# ---------------------------------------------------------------------------
# Tokens → the formats other tools read
# ---------------------------------------------------------------------------


def to_css_variables(tokens: TokenSet, *, selector: str = ":root") -> str:
    """CSS custom properties.

    Token names become kebab-case custom properties under one selector, so a
    stylesheet written against them tracks the brand without a build step.
    Millimetre values keep their unit — a length exported as a bare number is
    a length the browser will guess about.
    """
    lines = [
        "/* Generated by the ADOS Brand System. Do not edit.",
        f"   brand {tokens.brand_version} · {len(tokens)} tokens",
        "   Every value here is resolved from the brand; change the brand, not",
        "   this file. */",
        f"{selector} {{",
    ]
    for name, token in tokens.items():
        if isinstance(token.value, (list, dict)):
            continue                      # not expressible as a CSS value
        value = token.value
        if token.unit.value == "mm":
            value = f"{value}mm"
        elif token.unit.value == "pt":
            value = f"{value}pt"
        elif token.unit.value == "percent":
            value = f"{value}%"
        elif isinstance(value, bool):
            value = "1" if value else "0"
        lines.append(f"  --{name.replace('.', '-')}: {value};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def to_json(tokens: TokenSet, *, flat: bool = False) -> str:
    """Tokens as JSON — flat values, or the full record with provenance."""
    payload = tokens.flat() if flat else tokens.to_json_dict()
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def to_yaml(brand: Brand) -> str:
    """The brand definition as YAML.

    YAML because the repository's standards packs are YAML and a practice
    editing its brand by hand will find it friendlier than JSON. Falls back to
    JSON — which is valid YAML — when PyYAML is absent, rather than failing.
    """
    payload = json.loads(brand.to_json())
    try:
        import yaml
    except ImportError:                                    # pragma: no cover
        return (
            "# PyYAML is not installed; emitted as JSON, which is valid YAML.\n"
            + json.dumps(payload, indent=2)
            + "\n"
        )
    header = (
        f"# {brand.identity.name} — brand {brand.version} ({brand.status.value})\n"
        f"# Generated by the ADOS Brand System. content_hash "
        f"{brand.content_hash}\n"
    )
    return header + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)


def to_colour_table(tokens: TokenSet) -> list[dict[str, Any]]:
    """The palette with HEX, RGB, CMYK and L\\*, for a specification sheet.

    CMYK is a naive conversion and is labelled as such. A real print job takes
    its separations from a profiled conversion against the actual press and
    stock; a number produced here would be a number someone trusts. It is
    included because a printer asks for a starting point, not a final one.
    """
    from brand import colour as _c

    rows: list[dict[str, Any]] = []
    for name, token in sorted(tokens.namespace("color").items()):
        if not isinstance(token.value, str) or not token.value.startswith("#"):
            continue
        hex_value = token.value
        r, g, b = _c.to_rgb(hex_value)
        rows.append(
            {
                "token": name,
                "hex": hex_value,
                "rgb": f"{r} {g} {b}",
                "cmyk_uncalibrated": _naive_cmyk(r, g, b),
                "L_star": round(_c.l_star(hex_value), 1),
                "mono": _c.to_greyscale_hex(hex_value),
                "source": token.source,
            }
        )
    return rows


def _naive_cmyk(r: int, g: int, b: int) -> str:
    if (r, g, b) == (0, 0, 0):
        return "0 0 0 100"
    rc, gc, bc = r / 255, g / 255, b / 255
    k = 1 - max(rc, gc, bc)
    c = (1 - rc - k) / (1 - k)
    m = (1 - gc - k) / (1 - k)
    y = (1 - bc - k) / (1 - k)
    return " ".join(str(round(v * 100)) for v in (c, m, y, k))


# ---------------------------------------------------------------------------
# Browser-backed exports
# ---------------------------------------------------------------------------


def chromium_path() -> str | None:
    """The browser to use, or ``None``. Never guesses."""
    for candidate in _CHROMIUM_CANDIDATES:
        if Path(candidate).exists():
            return candidate
    return shutil.which("chromium") or shutil.which("google-chrome")


def browser_available() -> bool:
    if chromium_path() is None:
        return False
    try:
        import playwright.sync_api  # noqa: F401
    except ImportError:
        return False
    return True


@dataclass
class RasterResult:
    path: Path | None
    ok: bool
    reason: str = ""


def rasterise_svg(
    svg_path: Path | str, png_path: Path | str, *, width_px: int = 1200
) -> RasterResult:
    """SVG → PNG at a stated pixel width.

    A PNG is needed wherever SVG is not accepted — an email signature, a social
    post, a Word document. It is a derived artefact and the SVG remains the
    master; the manifest records both so nobody edits the raster.
    """
    svg_path, png_path = Path(svg_path), Path(png_path)
    if not browser_available():
        return RasterResult(
            None, False,
            "no Chromium and/or playwright available; the SVG is the master "
            "and the PNG can be produced later with "
            "`python -m brand.cli rasterise`",
        )
    from playwright.sync_api import sync_playwright

    # Preserve the aspect ratio declared by the SVG's own viewBox.
    import re

    text = svg_path.read_text()
    m = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', text)
    ratio = (float(m.group(2)) / float(m.group(1))) if m else 1.0
    height_px = max(1, round(width_px * ratio))

    png_path.parent.mkdir(parents=True, exist_ok=True)
    page_html = (
        f"<html><body style='margin:0'>"
        f"<img src='{svg_path.name}' style='width:{width_px}px;display:block'>"
        f"</body></html>"
    )
    holder = svg_path.parent / f".raster-{svg_path.stem}.html"
    holder.write_text(page_html)
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(executable_path=chromium_path())
            page = browser.new_page(
                viewport={"width": width_px, "height": height_px},
                device_scale_factor=1,
            )
            page.goto(holder.as_uri())
            page.screenshot(path=str(png_path), omit_background=True)
            browser.close()
    finally:
        holder.unlink(missing_ok=True)
    return RasterResult(png_path, True)


def html_to_pdf(
    html_path: Path | str, pdf_path: Path | str, *,
    page_format: str = "A4", landscape: bool = False,
    margin_mm: float = 0.0,
) -> RasterResult:
    """Print an HTML page to PDF through the browser's own print path.

    Used for the guidelines and the presentation. The alternative — laying the
    same content out a second time in reportlab — would mean two renderers
    that must be kept saying the same thing, and they would not.
    """
    html_path, pdf_path = Path(html_path), Path(pdf_path)
    if not browser_available():
        return RasterResult(
            None, False,
            "no Chromium and/or playwright available; the HTML is complete and "
            "print-ready — use the browser's Print to PDF, or install "
            "playwright to automate it",
        )
    from playwright.sync_api import sync_playwright

    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    margin = f"{margin_mm}mm"
    with sync_playwright() as pw:
        browser = pw.chromium.launch(executable_path=chromium_path())
        page = browser.new_page()
        page.goto(html_path.as_uri())
        page.emulate_media(media="print")
        page.pdf(
            path=str(pdf_path),
            format=page_format,
            landscape=landscape,
            print_background=True,
            margin={"top": margin, "bottom": margin,
                    "left": margin, "right": margin},
        )
        browser.close()
    return RasterResult(pdf_path, True)


# ---------------------------------------------------------------------------
# The asset manifest
# ---------------------------------------------------------------------------


@dataclass
class AssetRecord:
    """One file in the package, and enough metadata to trace it."""

    name: str
    type: str
    path: str
    format: str
    brand: str
    brand_version: str
    extra: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "type": self.type,
            "path": self.path,
            "format": self.format,
            "brand": self.brand,
            "brand_version": self.brand_version,
            **self.extra,
        }


class AssetInventory:
    """Collects every generated file with its metadata.

    The inventory is what makes the package auditable: the consistency check
    reads it, and a human can see at a glance which artefacts came from which
    brand version. An asset without a record is an asset nobody can trace back
    to a decision.
    """

    def __init__(self, brand: Brand, root: Path | str) -> None:
        self.brand = brand
        self.root = Path(root)
        self._records: list[AssetRecord] = []

    def add(
        self, path: Path | str, *, type: str, name: str | None = None,
        **extra: Any,
    ) -> Path:
        p = Path(path)
        rel = p.relative_to(self.root) if p.is_absolute() else p
        self._records.append(
            AssetRecord(
                name=name or p.stem,
                type=type,
                path=str(rel).replace("\\", "/"),
                format=p.suffix.lstrip("."),
                brand=self.brand.identity.name,
                brand_version=self.brand.version,
                extra=extra,
            )
        )
        return p

    def extend(self, records: Iterable[dict[str, Any]], *, type: str) -> None:
        for record in records:
            self._records.append(
                AssetRecord(
                    name=record.get("name", ""),
                    type=type,
                    path=record.pop("path", ""),
                    format=record.get("format", ""),
                    brand=self.brand.identity.name,
                    brand_version=self.brand.version,
                    extra={
                        k: v for k, v in record.items()
                        if k not in ("name", "format")
                    },
                )
            )

    @property
    def records(self) -> list[AssetRecord]:
        return list(self._records)

    def by_type(self) -> dict[str, list[AssetRecord]]:
        out: dict[str, list[AssetRecord]] = {}
        for r in self._records:
            out.setdefault(r.type, []).append(r)
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "brand": self.brand.identity.name,
            "brand_id": str(self.brand.brand_id),
            "brand_version": self.brand.version,
            "brand_status": self.brand.status.value,
            "content_hash": self.brand.content_hash,
            "ados_edition": self.brand.ados_edition,
            "asset_count": len(self._records),
            "assets": [r.to_dict() for r in self._records],
        }

    def write(self, path: Path | str | None = None) -> Path:
        p = Path(path) if path else self.root / "asset-inventory.json"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(self.to_dict(), indent=2) + "\n")
        return p
