"""Brand domain models. Pydantic v2, frozen, following ``schemas/v2_models.py``."""

from __future__ import annotations

from brand.models.architectural_language import (
    ArchitecturalLanguage,
    CameraLanguage,
    DiagramLanguage,
    DiagramProjection,
    DiagramStyle,
    DrawingLanguage,
    GraphicLayer,
    HatchDensity,
    LightingScenario,
    Lineweights,
    MaterialEntry,
    MaterialLanguage,
    RenderLanguage,
    RenderMood,
)
from brand.models.brand import (
    USABLE_STATUSES,
    Brand,
    BrandApplications,
    BrandStatus,
)
from brand.models.communication import Communication, Person, Tone
from brand.models.digital import (
    DigitalDirection,
    MotionLevel,
    NavStyle,
    SocialDirection,
    WebDirection,
)
from brand.models.identity import Identity, PersonalityAxis, PracticeScale
from brand.models.tokens import (
    TOKEN_NAMESPACES,
    Token,
    TokenBuilder,
    TokenSet,
    UndefinedTokenError,
    Unit,
)
from brand.models.visual_identity import (
    ColourSystem,
    ColourTreatment,
    CornerTreatment,
    GraphicLanguage,
    GraphicPrimitive,
    GridConfig,
    LogoConstruction,
    RoleClass,
    FontClass,
    FontFace,
    Grid,
    Imagery,
    Logo,
    LogoAsset,
    LogoUsageRules,
    SemanticColours,
    Spacing,
    Typography,
    TypeRole,
    VisualIdentity,
)

__all__ = [
    "RoleClass",
    "LogoConstruction",
    "GridConfig",
    "GraphicPrimitive",
    "GraphicLanguage",
    "CornerTreatment",
    "WebDirection",
    "SocialDirection",
    "NavStyle",
    "MotionLevel",
    "DigitalDirection",
    "ArchitecturalLanguage",
    "Brand",
    "BrandApplications",
    "BrandStatus",
    "CameraLanguage",
    "ColourSystem",
    "ColourTreatment",
    "Communication",
    "DiagramLanguage",
    "DiagramProjection",
    "DiagramStyle",
    "DrawingLanguage",
    "FontClass",
    "FontFace",
    "GraphicLayer",
    "Grid",
    "HatchDensity",
    "Identity",
    "Imagery",
    "LightingScenario",
    "Lineweights",
    "Logo",
    "LogoAsset",
    "LogoUsageRules",
    "MaterialEntry",
    "MaterialLanguage",
    "Person",
    "PersonalityAxis",
    "PracticeScale",
    "RenderLanguage",
    "RenderMood",
    "SemanticColours",
    "Spacing",
    "TOKEN_NAMESPACES",
    "Token",
    "TokenBuilder",
    "TokenSet",
    "Tone",
    "TypeRole",
    "Typography",
    "USABLE_STATUSES",
    "UndefinedTokenError",
    "Unit",
    "VisualIdentity",
]
